extends:
  - stylelint-config-recommended-scss
  - stylelint-config-recess-order
  - stylelint-config-prettier
rules:
  selector-pseudo-element-no-unknown:
    - true
    - ignorePseudoElements:
        - v-deep
